CREATE SEQUENCE REPLICATION.SEQ_RESOURCE
       MINVALUE 1
       MAXVALUE 999999999
     START WITH 1
   INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICATION.SEQ_RESOURCE TO SIS_REPLICATION;

CREATE TABLE REPLICATION.RESOURCE
(
    ID        NUMBER(9) DEFAULT REPLICATION.SEQ_RESOURCE.NEXTVAL NOT NULL,
    SCHEMA    VARCHAR(30) NOT NULL,
    TABLE     VARCHAR(30) NOT NULL,
    IDTOPIC   NUMBER(9) NOT NULL,
    SITUATION NUMBER(1) NOT NULL DEFAULT 1
)
TABLESPACE TBS_REPLICATION
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICATION.RESOURCE IS 'Resource table to manage the integration between kafka and oracle.';

COMMENT ON COLUMN REPLICATION.RESOURCE.ID IS 'Identification.';
COMMENT ON COLUMN REPLICATION.RESOURCE.SCHEMA IS 'Schema name.';
COMMENT ON COLUMN REPLICATION.RESOURCE.TABLE IS 'Table name.';
COMMENT ON COLUMN REPLICATION.RESOURCE.IDTOPIC IS 'Identification of topic.';
COMMENT ON COLUMN REPLICATION.RESOURCE.SITUATION IS 'Define if topic is (0) disabled or (1) enabled.';

ALTER TABLE REPLICATION.RESOURCE
        ADD CONSTRAINT REPLICATION.PK_RESOURCE
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_INDICES;

ALTER TABLE REPLICATION.RESOURCE
        ADD CONSTRAINT REPLICATION.FK_RESOURCE_TOPIC
    FOREIGN KEY (IDTOPIC)
 REFERENCES REPLICATION.TOPIC (ID);

GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICATION.RESOURCE TO SIS_REPLICATION;
