CREATE SEQUENCE REPLICATION.SEQ_BROKER
       MINVALUE 1
       MAXVALUE 999999999
     START WITH 1
   INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICATION.SEQ_BROKER TO SIS_REPLICATION;

CREATE TABLE REPLICATION.BROKER
(
    ID        NUMBER(9) DEFAULT REPLICATION.SEQ_BROKER.NEXTVAL NOT NULL,
    NAME      VARCHAR(128) NOT NULL,
    HOST      VARCHAR(256) NOT NULL,
    PORT      NUMBER(9) NOT NULL,
    SITUATION NUMBER(1) NOT NULL DEFAULT 1
)
TABLESPACE TBS_REPLICATION
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICATION.BROKER IS 'Define an broker that receive messages.';

COMMENT ON COLUMN REPLICATION.BROKER.ID IS 'Broker identification.';
COMMENT ON COLUMN REPLICATION.BROKER.NAME IS 'Broker name.';
COMMENT ON COLUMN REPLICATION.BROKER.HOST IS 'Broker host.';
COMMENT ON COLUMN REPLICATION.BROKER.PORT IS 'Broker port.';
COMMENT ON COLUMN REPLICATION.BROKER.SITUATION IS 'Define if topic is (0) disabled or (1) enabled.';

ALTER TABLE REPLICATION.BROKER
        ADD CONSTRAINT REPLICATION.PK_BROKER
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_INDEXES;

GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICATION.BROKER TO SIS_REPLICATION;
