CREATE SEQUENCE DIABLOIV.SEQ_PLAYER
       MINVALUE 1
       MAXVALUE 999999999
     START WITH 1
   INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON DIABLOIV.SEQ_PLAYER TO SIS_DIABLOIV;

CREATE TABLE DIABLOIV.PLAYER
(
    ID    NUMBER(9) DEFAULT REPLICATION.SEQ_PLAYER.NEXTVAL NOT NULL,
    NAME  VARCHAR(30) NOT NULL,
    LEVEL NUMBER(3) NOT NULL
)
TABLESPACE TBS_DIABLOIV
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE DIABLOIV.PLAYER IS 'Resource table to manage the integration between kafka and oracle.';

COMMENT ON COLUMN DIABLOIV.PLAYER.ID IS 'Identification.';
COMMENT ON COLUMN DIABLOIV.PLAYER.SCHEMA IS 'Player name.';
COMMENT ON COLUMN DIABLOIV.PLAYER.TABLE IS 'Player birth.';

ALTER TABLE DIABLOIV.PLAYER
        ADD CONSTRAINT DIABLOIV.PK_PLAYER
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_INDICES;

GRANT SELECT, INSERT, UPDATE, DELETE ON DIABLOIV.PLAYER TO SIS_REPLICATION;
