CREATE OR REPLACE TRIGGER REPLICATION.TRG_PLAYER
 AFTER INSERT OR DELETE OR UPDATE ON REPLICATION.PLAYER
BEGIN
  IF INSERTING THEN
  BEGIN
    REPLICATION.CHANGE_DATA_CAPTURE.PUBLISH('{\"ID\":1,\"NOME\":\"RAFAEL\",\"IDADE\":\"32\"}', 'POST');
  END
  ELSIF UPDATING THEN
  BEGIN
    REPLICATION.CHANGE_DATA_CAPTURE.PUBLISH('{\"ID\":1,\"NOME\":\"RAFAEL\"}', 'PUT');
  END
  ELSIF DELETING THEN
  BEGIN
    REPLICATION.CHANGE_DATA_CAPTURE.PUBLISH('1', 'DELETE');
  END;
END;
