CREATE SEQUENCE REPLICACAO.SEQ_FILA
       MINVALUE 1
       MAXVALUE 999999999
          START WITH 1
      INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICACAO.SEQ_FILA TO SIS_REPLICACAO;

CREATE TABLE REPLICACAO.FILA
(
    ID            NUMBER(9) DEFAULT REPLICACAO.SEQ_FILA.NEXTVAL NOT NULL,
    ESQUEMA       VARCHAR2(30) NOT NULL,
    TABELA        VARCHAR2(30) NOT NULL,
    OPERACAO      NUMBER(1) NOT NULL,
    CONTEUDO      VARCHAR2(4000) NOT NULL,
    PROCESSADO    NUMBER(1) DEFAULT 0 NOT NULL,
    DATA_REGISTRO TIMESTAMP(6)WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
TABLESPACE TBS_REPLICACAO
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
      MAXEXTENTS UNLIMITED
   )
PARTITION BY LIST (PROCESSADO)
(
    PARTITION P_PROCESSADO_NAO VALUES (0),
    PARTITION P_PROCESSADO_SIM VALUES (1)
);

COMMENT ON TABLE REPLICACAO.FILA                IS 'Define fila de mensagens que devem ser reprocessadas.';

COMMENT ON COLUMN REPLICACAO.FILA.ID            IS 'Identificação da fila.';
COMMENT ON COLUMN REPLICACAO.FILA.ESQUEMA       IS 'Nome do esquema que contém a tabela que deve ser reprocessada.';
COMMENT ON COLUMN REPLICACAO.FILA.TABELA        IS 'Nome da tabela que deve ser reprocessada.';
COMMENT ON COLUMN REPLICACAO.FILA.OPERACAO      IS 'Define se o tópico será usado para uma operação de (1) criação ou (2) atualização ou (3) deleção.';
COMMENT ON COLUMN REPLICACAO.FILA.CONTEUDO      IS 'Conteúdo que deve ser processado.';
COMMENT ON COLUMN REPLICACAO.FILA.PROCESSADO    IS 'Indica se a fila foi devidamente processada.';
COMMENT ON COLUMN REPLICACAO.FILA.DATA_REGISTRO IS 'Define se o broker está (0) desativado or (1) ativado.';

ALTER TABLE REPLICACAO.FILA
        ADD CONSTRAINT PK_FILA
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_REPLICACAO;

ALTER TABLE REPLICACAO.FILA
        ADD CONSTRAINT CK_FILA_OPERACAO
      CHECK (OPERACAO IN (1, 2, 3));
      
GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICACAO.FILA TO SIS_REPLICACAO;
