CREATE SEQUENCE REPLICACAO.SEQ_LOG
       MINVALUE 1
       MAXVALUE 999999999
          START WITH 1
      INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICACAO.SEQ_LOG TO SIS_REPLICACAO;

CREATE TABLE REPLICACAO.LOG
(
    ID            NUMBER(9) DEFAULT REPLICACAO.SEQ_LOG.NEXTVAL NOT NULL,
    TITULO        VARCHAR2(200) NOT NULL,
    DESCRICAO     VARCHAR2(4000) NOT NULL,
    IDFILA        NUMBER(9) NOT NULL,
    ORIGEM        NUMBER(9) NOT NULL,
    DATA_REGISTRO TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
)
TABLESPACE TBS_REPLICACAO
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICACAO.LOG                IS 'Define um log.';

COMMENT ON COLUMN REPLICACAO.LOG.ID            IS 'Identificação do log.';
COMMENT ON COLUMN REPLICACAO.LOG.TITULO        IS 'Título do log com um resumo sobre o problema ocorrido.';
COMMENT ON COLUMN REPLICACAO.LOG.DESCRICAO     IS 'Descrição da falha ocorrida a nível de sistema, pode ser uma stacktrace, exception, etc.';
COMMENT ON COLUMN REPLICACAO.LOG.IDFILA        IS 'Identificação da fila derivada do erro ocorrido.';
COMMENT ON COLUMN REPLICACAO.LOG.ORIGEM        IS 'Define a camada de origem da falha, (1) Trigger do Oracle, (2) Pacote CDC do Oracle ou (3) API de Integração.';
COMMENT ON COLUMN REPLICACAO.LOG.DATA_REGISTRO IS 'Data de registro do log.';

ALTER TABLE REPLICACAO.LOG
        ADD CONSTRAINT PK_LOG
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_REPLICACAO;

ALTER TABLE REPLICACAO.LOG
        ADD CONSTRAINT FK_LOG_FILA
    FOREIGN KEY (IDFILA)
 REFERENCES REPLICACAO.FILA (ID);

ALTER TABLE REPLICACAO.LOG
        ADD CONSTRAINT CK_LOG_ORIGEM
      CHECK (ORIGEM IN (1, 2, 3));

GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICACAO.LOG TO SIS_REPLICACAO;
