CREATE SEQUENCE REPLICACAO.SEQ_COTACAO
       MINVALUE 1
       MAXVALUE 999999999
     START WITH 1
   INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICACAO.SEQ_COTACAO TO SIS_REPLICACAO;

CREATE TABLE REPLICACAO.COTACAO
(
    ID       NUMBER(9) DEFAULT REPLICACAO.SEQ_COTACAO.NEXTVAL NOT NULL,
    REGISTRO DATE DEFAULT SYSDATE NOT NULL,
    IDMOEDA  NUMBER(9) NOT NULL,
    COMPRA   NUMBER(9, 9) NOT NULL,
    VENDA    NUMBER(9, 9) NOT NULL
)
TABLESPACE TBS_REPLICACAO
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICACAO.COTACAO IS 'Registro de cotação.';

COMMENT ON COLUMN REPLICACAO.COTACAO.ID IS 'Identificação da cotação.';
COMMENT ON COLUMN REPLICACAO.COTACAO.IDMOEDA IS 'Identificação da moeda.';
COMMENT ON COLUMN REPLICACAO.COTACAO.COMPRA IS 'Valor de compra.';
COMMENT ON COLUMN REPLICACAO.COTACAO.VENDA IS 'Valor de venda.';

ALTER TABLE REPLICACAO.COTACAO
        ADD CONSTRAINT PK_COTACAO
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_REPLICACAO;

ALTER TABLE REPLICACAO.COTACAO
        ADD CONSTRAINT FK_COTACAO_MOEDA
    FOREIGN KEY (IDMOEDA)
 REFERENCES REPLICACAO.MOEDA (ID);
  
GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICACAO.COTACAO TO SIS_REPLICACAO;
