CREATE SEQUENCE REPLICACAO.SEQ_MOEDA
       MINVALUE 1
       MAXVALUE 999999999
     START WITH 1
   INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICACAO.SEQ_MOEDA TO SIS_REPLICACAO;

CREATE TABLE REPLICACAO.MOEDA
(
    ID      NUMBER(9) DEFAULT REPLICACAO.SEQ_MOEDA.NEXTVAL NOT NULL,
    MOEDA   VARCHAR2(32) NOT NULL,
    SIMBOLO VARCHAR2(4) NOT NULL
)
TABLESPACE TBS_REPLICACAO
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICACAO.MOEDA IS 'Registro de moeda.';

COMMENT ON COLUMN REPLICACAO.MOEDA.ID IS 'Identificação da moeda.';
COMMENT ON COLUMN REPLICACAO.MOEDA.MOEDA IS 'Nome da moeda.';
COMMENT ON COLUMN REPLICACAO.MOEDA.SIMBOLO IS 'Símbolo da moeda.';

ALTER TABLE REPLICACAO.MOEDA
        ADD CONSTRAINT PK_MOEDA
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_REPLICACAO;

GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICACAO.MOEDA TO SIS_REPLICACAO;
