CREATE SCHEMA REPLICATION;
CREATE SCHEMA AUTHORIZATION SIS_REPLICATION;

GRANT CREATE SESSION TO SIS_REPLICATION;
GRANT CREATE TABLE TO SIS_REPLICATION;
GRANT CREATE VIEW TO SIS_REPLICATION;
GRANT CREATE ANY TRIGGER TO SIS_REPLICATION;
GRANT CREATE ANY PROCEDURE TO SIS_REPLICATION;
GRANT CREATE SEQUENCE TO SIS_REPLICATION;
GRANT CREATE SYNONYM TO SIS_REPLICATION;
