CREATE SEQUENCE REPLICATION.SEQ_TOPIC
       MINVALUE 1
       MAXVALUE 999999999
     START WITH 1
   INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICATION.SEQ_TOPIC TO SIS_REPLICATION;

CREATE TABLE REPLICATION.TOPIC
(
    ID         NUMBER(9) DEFAULT REPLICATION.SEQ_TOPIC.NEXTVAL NOT NULL,
    NAME       VARCHAR(128) NOT NULL,
    REPLICAS   NUMBER(2) NULL,
    PARTITIONS NUMBER(2) NULL,
    SITUATION  NUMBER(1) NOT NULL DEFAULT 1
)
TABLESPACE TBS_REPLICATION
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICATION.TOPIC IS 'Define a topic on kafka.';

COMMENT ON COLUMN REPLICATION.TOPIC.ID IS 'Identification.';
COMMENT ON COLUMN REPLICATION.TOPIC.NAME IS 'Topic name';
COMMENT ON COLUMN REPLICATION.TOPIC.REPLICAS IS 'Quantity of replicas.';
COMMENT ON COLUMN REPLICATION.TOPIC.PARTITIONS IS 'Quantity of partitions.';
COMMENT ON COLUMN REPLICATION.TOPIC.SITUATION IS 'Define if topic is (0) disabled or (1) enabled.';

ALTER TABLE REPLICATION.TOPIC
        ADD CONSTRAINT REPLICATION.PK_TOPIC
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_INDEXES;

GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICATION.TOPIC TO SIS_REPLICATION;
