CREATE SEQUENCE REPLICACAO.SEQ_RECURSO
       MINVALUE 1
       MAXVALUE 999999999
          START WITH 1
      INCREMENT BY 1
        NOCACHE;

GRANT SELECT ON REPLICACAO.SEQ_RECURSO TO SIS_REPLICACAO;

CREATE TABLE REPLICACAO.RECURSO
(
    ID       NUMBER(9) DEFAULT REPLICACAO.SEQ_RECURSO.NEXTVAL NOT NULL,
    ESQUEMA  VARCHAR2(30) NOT NULL,
    TABELA   VARCHAR2(30) NOT NULL,
    IDTOPICO NUMBER(9) NOT NULL,
    SITUACAO NUMBER(1) DEFAULT 1 NOT NULL 
)
TABLESPACE TBS_REPLICACAO
   PCTFREE 10
  INITRANS 1
  MAXTRANS 255
   STORAGE
   (
       INITIAL 64K
       NEXT 1M
       MINEXTENTS 1
       MAXEXTENTS UNLIMITED
   );

COMMENT ON TABLE REPLICACAO.RECURSO           IS 'Recurso usado para integrar o oracle com o broker.';

COMMENT ON COLUMN REPLICACAO.RECURSO.ID       IS 'Identificação do recurso.';
COMMENT ON COLUMN REPLICACAO.RECURSO.ESQUEMA  IS 'Nome do esquema.';
COMMENT ON COLUMN REPLICACAO.RECURSO.TABELA   IS 'Nome da tabela.';
COMMENT ON COLUMN REPLICACAO.RECURSO.IDTOPICO IS 'Identificação do tópico.';
COMMENT ON COLUMN REPLICACAO.RECURSO.SITUACAO IS 'Define se o tópico está (0) desabilitado ou (1) habilitado.';

ALTER TABLE REPLICACAO.RECURSO
        ADD CONSTRAINT PK_RECURSO
    PRIMARY KEY (ID)
      USING INDEX TABLESPACE TBS_REPLICACAO;

ALTER TABLE REPLICACAO.RECURSO
        ADD CONSTRAINT FK_RECURSO_TOPICO
    FOREIGN KEY (IDTOPICO)
 REFERENCES REPLICACAO.TOPICO (ID);

ALTER TABLE REPLICACAO.RECURSO
        ADD CONSTRAINT CK_RECURSO_SITUACAO
      CHECK (SITUACAO IN (0, 1));

GRANT SELECT, INSERT, UPDATE, DELETE ON REPLICACAO.RECURSO TO SIS_REPLICACAO;
