DROP SEQUENCE REPLICACAO.SEQ_BROKER;
DROP TABLE REPLICACAO.BROKER;

DROP SEQUENCE REPLICACAO.SEQ_FILA;
DROP TABLE REPLICACAO.FILA;

DROP SEQUENCE REPLICACAO.SEQ_LOG;
DROP TABLE REPLICACAO.LOG;

DROP SEQUENCE REPLICACAO.SEQ_RECURSO;
DROP TABLE REPLICACAO.RECURSO;

DROP SEQUENCE REPLICACAO.SEQ_TOPICO;
DROP TABLE REPLICACAO.TOPICO;

DROP SEQUENCE REPLICACAO.SEQ_COTACAO;
DROP TABLE REPLICACAO.COTACAO;

DROP SEQUENCE REPLICACAO.SEQ_MOEDA;
DROP TABLE REPLICACAO.MOEDA;
