-- SELECT M.*, M.ROWID FROM REPLICACAO.TOPICO M;
-- SELECT M.*, M.ROWID FROM REPLICACAO.RECURSO M;

-- INSERT INTO REPLICACAO.RECURSO (ESQUEMA, TABELA, IDTOPICO, SITUACAO) VALUES ('REPLICACAO', 'MOEDA', 1, 1);
-- INSERT INTO REPLICACAO.RECURSO (ESQUEMA, TABELA, IDTOPICO, SITUACAO) VALUES ('REPLICACAO', 'MOEDA', 2, 1);
-- INSERT INTO REPLICACAO.RECURSO (ESQUEMA, TABELA, IDTOPICO, SITUACAO) VALUES ('REPLICACAO', 'MOEDA', 3, 1);

-- SELECT M.*, M.ROWID FROM REPLICACAO.MOEDA M;

INSERT INTO REPLICACAO.MOEDA (MOEDA, SIMBOLO) VALUES ('PESO ARGENTINO', '$');
INSERT INTO REPLICACAO.MOEDA (MOEDA, SIMBOLO) VALUES ('EURO', '€');
INSERT INTO REPLICACAO.MOEDA (MOEDA, SIMBOLO) VALUES ('IENE', '¥');
INSERT INTO REPLICACAO.MOEDA (MOEDA, SIMBOLO) VALUES ('LEMPIRA', 'L');
INSERT INTO REPLICACAO.MOEDA (MOEDA, SIMBOLO) VALUES ('LIBRA ESTERLINA', '£');
