CREATE OR REPLACE TRIGGER REPLICACAO.TRG_COTACAO
 AFTER INSERT OR DELETE OR UPDATE ON REPLICACAO.COTACAO
   FOR EACH ROW
BEGIN
  IF INSERTING THEN
    REPLICACAO.CHANGE_DATA_CAPTURE.PUBLISH
    (
      P_ESQUEMA  => 'REPLICACAO',
      P_TABELA   => 'COTACAO',
      P_OPERACAO => 1,
      P_ID       => :NEW.ID,
      P_CONTEUDO => ''
    );
  ELSIF UPDATING THEN
    REPLICACAO.CHANGE_DATA_CAPTURE.PUBLISH
    (
      P_ESQUEMA  => 'REPLICACAO',
      P_TABELA   => 'COTACAO',
      P_OPERACAO => 1,
      P_ID       => :NEW.ID,
      P_CONTEUDO => ''
    );
  ELSIF DELETING THEN
    REPLICACAO.CHANGE_DATA_CAPTURE.PUBLISH
    (
      P_ESQUEMA  => 'REPLICACAO',
      P_TABELA   => 'COTACAO',
      P_OPERACAO => 1,
      P_ID       => :NEW.ID,
      P_CONTEUDO => ''
    );
  END;
END;
